# font_size 12.0

map kitty_mod+y launch --stdin-source=@screen_scrollback --type=overlay nvim -R + -c 'command Q qall!'
map kitty_mod+g launch --stdin-source=@last_cmd_output --type=overlay nvim -R -c 'command Q qall!'
map kitty_mod+a>e launch --type=tab nvim ~/.config/kitty/kitty.conf
