new_tab tool
layout splits
cd ~
launch --hold trans -x 127.0.0.1:7890 :en+zh
launch --hold --location=vsplit --bias=45 ghci
launch --var window=last --location=hsplit --bias=65 zsh
focus_matching_window var:window=last
