new_tab main
layout splits
cd ~
launch --var window=first zsh
launch --hold --location=vsplit --bias=40 zsh -c "peaclock || clock-rs || tty-clock -c"
launch --location=hsplit --bias=75 zsh
focus_matching_window var:window=first

# new_tab work
# layout splits
# cd ~/Workspace/
# launch --var window=first zsh
# launch --location=vsplit zsh
# focus_matching_window var:window=first

# # 用于需要持久化的工作，比如claude code
# new_tab persist
# layout splits
# launch --hold --var IS_TMUX=true zsh -c "source $HOME/.tmuxrc; tmux at -t main; kitten @ set-user-vars IS_TMUX"

new_tab herdr
cd ~/Workspace/
layout splits
# launch --hold --var IS_HERDR=true herdr
launch --hold --var IS_HERDR=true zsh -c "herdr; kitten @ set-user-vars IS_HERDR"

new_tab tool
layout splits
cd ~
launch --hold zsh -c "trans -x 127.0.0.1:7892 :en+zh"
launch --hold --location=vsplit --bias=45 ghci
launch --location=hsplit --bias=65 zsh
