new_tab main
layout splits
cd ~
launch --var window=first zsh
launch --location=vsplit --bias=40 zsh -c "peaclock || clock-rs || tty-clock -c || zsh"
launch --location=hsplit --bias=75 zsh
focus_matching_window var:window=first

new_tab work
layout splits
cd ~/Workspace/
launch --var window=first zsh
launch --location=vsplit zsh
focus_matching_window var:window=first

# # 用于需要持久化的工作，比如claude code
# new_tab persist
# layout splits
# launch --var IS_TMUX=true zsh -c "source $HOME/.tmuxrc; exec tmux at -t main"

new_tab tool
layout splits
cd ~
launch zsh -c "trans -x 127.0.0.1:7892 :en+zh || zsh"
launch --location=vsplit --bias=45 zsh -c "ghci || zsh"
launch --location=hsplit --bias=65 zsh
